name: Checks (PR)

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - 'biome.json'
      - 'package.json'
      - 'tsconfig.json'
      - '!**/*.config.ts'
      - '!**/.*/**'
      - '!**/__*__/**'
      - '**/__test__/**'
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun check:apply
      - run: bun type-check
      - run: bun test
