name: Checks (Push/PR - Conditional)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - 'biome.json'
      - 'package.json'
      - 'bun.lockb'
      - 'yan.lock'
      - '!**/__examples__/**'
      - '!**/__scripts__/**'
    types: [opened, reopened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: diff <(bun bun.lockb) yarn.lock
      - run: bun install
      - run: bun run lint:fix
      - run: bun run typecheck
      - run: bun test
