name: Checks (Push/PR - Conditional)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - 'biome.json'
      - 'package.json'
      - 'bun.lockb'
      - 'yan.lock'
      - '!**/__examples__/**'
      - '!**/__scripts__/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - 'biome.json'
      - 'package.json'
      - 'bun.lockb'
      - 'yan.lock'
      - '!**/__examples__/**'
      - '!**/__scripts__/**'
    types: [opened, reopened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: "[ \"$(cat yarn.lock | md5sum)\" == \"$(bun bun.lockb | md5sum)\" ]"
      - run: bun install
      - run: bun check:apply
      - run: bun type-check
      - run: bun test
