name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  changesets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      pages: write
    steps:
      # Build
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run lint:fix
      - run: bun run typecheck
      - run: bun test
      - run: bun run build

      # Version/publish
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: changesets
        uses: changesets/action@v1
        with:
          title: '[ci] release'
          commit: '[ci] release'
          publish: bun changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Docs
      - if: steps.changesets.outputs.published == 'true'
        run: |
          bun install
          bun run build
        working-directory: ./website
      - if: steps.changesets.outputs.published == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/dist
      - if: steps.changesets.outputs.published == 'true'
        uses: actions/deploy-pages@v4
